Fleshed out pre-push hook and fixed eslintrc to work with prettier

diff --git a/git_hooks/pre-push b/git_hooks/pre-push
--- a/git_hooks/pre-push
+++ b/git_hooks/pre-push
@@ -22,7 +22,33 @@
 remote="$1"
 url="$2"
 
-z40=0000000000000000000000000000000000000000
+# Color definitions
+RED='\033[0;31m'
+GREEN='\033[0;32m'
+YELLOW='\033[1;33m'
+NC='\033[0m' # No Color
 
+echo -e "${YELLOW}Checking Prettier Formatting:"
 yarn run prettier --check ./
-exit 1
+prettier_exit_code="$?"
+
+echo -e "${YELLOW}Checking ESLint rules:"
+yarn run eslint ./
+eslint_exit_code="$?"
+
+# Print error messsages
+if [[ "$prettier_exit_code" != "0" ]]; then
+  echo -e "${RED}Prettier failed"
+  exit 1
+else
+  echo -e "${GREEN}Prettier passed"
+fi
+
+if [[ "$eslint_exit_code" != "0" ]]; then
+  echo -e "${RED}ESLint failed"
+  exit 1
+else
+  echo -e "${GREEN}ESLint passed"
+fi
+
+exit 0
