Fixed typescript issues with new Formik additions, added typescript type checking to pre-push script, added type_check and all_check scripts for convenience

diff --git a/git_hooks/pre-push b/git_hooks/pre-push
--- a/git_hooks/pre-push
+++ b/git_hooks/pre-push
@@ -29,11 +29,15 @@ YELLOW='\033[1;33m'
 NC='\033[0m' # No Color
 
 echo "${YELLOW}Checking Prettier Formatting:"
-yarn run prettier --check ./
+yarn format_check
 prettier_exit_code="$?"
 
+echo "${YELLOW}Checking Typescript:"
+yarn type_check
+typescript_exit_code="$?"
+
 echo "${YELLOW}Checking ESLint rules:"
-yarn run eslint ./
+yarn lint_check
 eslint_exit_code="$?"
 
 # Print error messsages
@@ -44,6 +48,13 @@ if [ "$prettier_exit_code" != "0" ]; then
   exit_code=1
 else
   echo "${YELLOW}Prettier: ${GREEN}passed"
+fi
+
+if [ "$typescript_exit_code" != "0" ]; then
+  echo "${YELLOW}Typescript check ${RED}failed"
+  exit_code=1
+else
+  echo "${YELLOW}Typescript check ${GREEN}passed"
 fi
 
 if [ "$eslint_exit_code" != "0" ]; then
